name: showvis
description: Search and share all your favorite TV Shows
publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  riverpod: ^1.0.3
  http_client: ^1.5.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  flutter_riverpod: ^1.0.4
  go_router: ^4.3.0
  cached_network_image: ^3.2.2
  html: ^0.15.0
  intl: ^0.17.0
  app_bar_with_search_switch: ^1.3.6
  very_good_infinite_list: ^0.4.1
  path_provider: ^2.0.11
  splash_screen_view: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/no_image.png
    - assets/logo.png

splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#673ab7"
  #background_image: "assets/logo.png"

  # Optional parameters are listed below.
  image: assets/logo.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  android: true
  ios: true
  #web: false

  android_gravity: center
  ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true

  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
